apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      format json
      read_from_head true
    </source>

    <match **>
      @type opensearch
      host ${OPENSEARCH_HOST}
      port 443
      scheme https
      ssl_verify true
      index_name fluentd
      include_tag_key true
      type_name _doc
      reconnect_on_error true
      reload_connections false
      logstash_format true
      logstash_prefix fluentd
      time_key time
      time_key_format %Y-%m-%dT%H:%M:%S.%NZ
      <buffer>
        @type file
        path /var/log/fluentd-buffers/opensearch
        flush_mode interval
        flush_interval 5s
        retry_type exponential_backoff
        retry_forever true
        chunk_limit_size 2m
        queue_limit_length 32
        overflow_action block
      </buffer>
    </match>
